# Generated by Django 5.2.1 on 2025-05-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipos',
            options={'ordering': ['id'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelTable(
            name='tipos',
            table='pokemon_type',
        ),
    ]
