# Generated by Django 5.2.1 on 2025-05-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('vida', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defensa', models.IntegerField()),
                ('velocidad', models.IntegerField(null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
