# Generated by Django 5.2.1 on 2025-05-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_alter_pokemons_altura_alter_pokemons_peso'),
        ('tipos', '0002_alter_tipos_options_alter_tipos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='types',
            field=models.ManyToManyField(related_name='pokemons', to='tipos.tipos'),
        ),
    ]
